services:
  api:
    build:
      context: ./api/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5001", "--reload"]
    environment:
      DATABASE_URL: postgres://admin:admin123@postgres_db:5432/master_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: master_db
    depends_on:
      - db
    ports:
      - "5001:5001"
    networks:
      - default

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: master_db
    volumes:
      - ./database/app/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - default
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "8050:8050"
    depends_on:
      - api
    networks:
      - default
networks:
  default:
    driver: bridge
